### ISSUE TITLE
`fellingdater` on rOpenSci

### ISSUE THREAD

**Issue by hanecakr** [RonaldVisser/Dendro_R#1]
Hi Ronald,

Wanted to let you know that the fellingdater package has passed a software review and is now available via the GitHub repo of rOpenSci.

Therefore, could you please update in your overview of dendro related R-packages:

- the name of the package, which changed from `fellingdateR` to `fellingdater`
-  change the url to https://docs.ropensci.org/fellingdater/ 

Thanks!
Kristof

**Comment by RonaldVisser** [comment]
Hi Kristof,

Congrats! That is cool! I have updated this in the site. Thanks for pointing out

Ronald
